# Generated by Django 3.0.8 on 2020-07-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="is_completed", new_name="completed",
        ),
        migrations.RenameField(
            model_name="project", old_name="is_started", new_name="in_progress",
        ),
        migrations.AddField(
            model_name="project",
            name="no_progress",
            field=models.BooleanField(default=True),
        ),
    ]
