# Generated by Django 3.0.8 on 2020-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200711_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion',
            field=models.FloatField(default=0),
        ),
    ]
