# Generated by Django 3.0.8 on 2020-08-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task_order',
            field=models.PositiveIntegerField(choices=[(0, 'priority'), (1, 'difficulty'), (2, 'creation date'), (3, 'deadline date')], default=0),
        ),
    ]
