# Generated by Django 3.0.8 on 2020-09-01 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_task_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='in_progress',
        ),
        migrations.RemoveField(
            model_name='project',
            name='no_progress',
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 13, 47, 56, 925495)),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.IntegerField(choices=[(0, 'no progress'), (1, 'in progress'), (2, 'completed')], default=0),
        ),
    ]
