# Generated by Django 3.0.8 on 2020-07-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True, max_length=110, unique=True),
        ),
    ]
