# Generated by Django 3.0.8 on 2020-07-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_state"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="completed",),
        migrations.RemoveField(model_name="task", name="in_progress",),
        migrations.RemoveField(model_name="task", name="no_progress",),
        migrations.AlterField(
            model_name="task",
            name="state",
            field=models.IntegerField(
                choices=[(0, "no progress"), (1, "in progress"), (2, "completed")],
                default=0,
            ),
        ),
    ]
