# Generated by Django 3.0.8 on 2020-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_auto_20200729_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "low"),
                    (2, "below medium"),
                    (3, "medium"),
                    (4, "above medium"),
                    (5, "high"),
                ],
                default=2,
            ),
        ),
    ]
