# Generated by Django 3.0.8 on 2020-08-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_auto_20200803_1143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="state",
            field=models.IntegerField(
                choices=[(0, "no progress"), (1, "in progress"), (2, "completed")],
                default=0,
            ),
        ),
    ]
