# Generated by Django 3.0.8 on 2020-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_auto_20200803_1342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
