# Generated by Django 3.0.8 on 2020-08-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20200803_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
