# Generated by Django 3.0.8 on 2020-08-12 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20200811_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 8, 43, 9, 105789)),
        ),
    ]
