# Generated by Django 3.0.8 on 2020-09-25 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_auto_20200925_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 13, 50, 5, 172563)),
        ),
    ]
