# Generated by Django 3.0.8 on 2020-08-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='completion',
            field=models.FloatField(default=0),
        ),
    ]
